name: EasyHook-Package

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: EasyHook.sln

jobs:
  package:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{github.workspace}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Install
        working-directory: ${{github.workspace}}
        run: Tools\ci_install.bat vs2019
        shell: cmd

      - name: Build Package
        working-directory: ${{github.workspace}}
        run: Tools\build_package.bat vs2019
        shell: cmd
