name: EasyHook-Package

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: EasyHook.sln

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
        
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Install
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Tools\ci_install.bat

    - name: Build Package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Tools\build-package.bat
