name: EasyHook-Driver

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: EasyHookSys.sln

jobs:
  driver:
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [windows-2022]
        net: [Win10]
        config: [Debug, Release]
        platform: [x64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{github.workspace}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{github.workspace}}
        run: msbuild /m /p:Configuration=${{ matrix.net }}-${{ matrix.config }} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}

